### PR TITLE
Add link to Linux installer

### PR DESCRIPTION
**Pull request by VirxEC**
I developed with inspect element :)

image

### CODE REVIEW

**Comment by tarehart** [comment]
Good idea! I would prefer that people be routed through https://github.com/RLBot/RLBot/wiki/Operating-System-Support so they get full context on our level of Linux support, easier for us to update, etc.

Maybe something like "Download RLBot for Windows | see other OS options"

**Comment by VirxEC** [comment]
I'll do that and I'll update the wiki regarding Linux

**Comment by VirxEC** [comment]
New page: 
image

**Comment by VirxEC** [comment]
No problem!

**Pull request merged**
