### PR TITLE
Fix youtube link

### PR DESCRIPTION
**Pull request by DomNomNom**

### CODE REVIEW

**Comment by tarehart** [comment]
Thanks Dom. I'm currently trying to reclaim the /RLBot url, if I succeed I'll revert this.

**Comment by DomNomNom** [comment]
I've set it up to be /c/RLBotOfficial today and tried to make it /c/RLBot but youtube kinda forced me to add a suffix to it.
Let me know how you go

**Comment by tarehart** [comment]
The /RLBot url had still been held by the old personal account. I released it, and I'm hoping Google will eventually notice it's available again. "Note that once you remove a custom URL it may become free to be claimed by another creator."

**Comment by DomNomNom** [comment]
Thanks for the context. :+1:

**Pull request merged**
