### PR TITLE
Add FAQ page

### PR DESCRIPTION
**Pull request by NicEastvillage**
An FAQ page with the same FAQs as on the Discord server.

### CODE REVIEW

**Comment by swz-gh** [comment]
can i see a screenshot? 👉🏼 👈🏼

**Comment by NicEastvillage** [comment]
billede

**Comment by swz-gh** [comment]
Maybe add ids to every card-title so you can link to it like this: `https://rlbot.org/faq#can-rlbot-be-used-online`

**Comment by NicEastvillage** [comment]
Good idea. Also added the field dimensions image.

**Review by VirxEC — APPROVED** [review]
Looks good to me!

**Pull request merged**
