### PR TITLE
JavaScript card

### PR DESCRIPTION
**Pull request by naturecodevoid**
Links will probably need to be changed in the future.

### CODE REVIEW

**Comment by tarehart** [comment]
Is that port conflict stuff sorted out now?

**Comment by naturecodevoid** [comment]
As far as I'm aware no progress has been made since late august.

**Comment by naturecodevoid** [comment]
oops, sorry East

**Comment by SuperVK** [comment]
port conflict is fixed (if the bot owner sets a custom port); but there are some issues left.
1. Eldest wanted to add multi threading
2. I wanna make the dev environment setup easier ([using npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b))
3. Running the bots in a competition is still too hard (Eldest has already got a binary with the packages ready, but I don't think that's actually implemented yet)

**Comment by VirxEC** [comment]
no longer required

**Pull request closed without merging**
