### PR TITLE
Update the tournaments page

### PR DESCRIPTION
**Pull request by VirxEC**
Added winners of RLBot Championship 2020
Added card for Triple Threat 2020
Removed League Play link (I just commented it out, so if we ever get it running again just uncomment it)
Moved all winners to a dropdown menu to prevent spoilers

Winners collapsed:
image

Winners expanded (you can do each one individually):
image

Codename Cyro doesn't have a GitHub repo, so he doesn't get a link >:(

### CODE REVIEW

**Comment by VirxEC** [comment]
I'm also going to see if I can get something working in regards to #18

**Comment by VirxEC** [comment]
How does this look as a solution to #18?

image
image

**Comment by NicEastvillage** [comment]
Yeah, that would be a great way to prevent spoilers!

**Review by NicEastvillage — APPROVED** [review]

**Comment by AlexanderBelooussov** [comment]
> Codename Cyro doesn't have a GitHub repo, so he doesn't get a link >:(
fight me

**Comment by VirxEC** [comment]
I still need to make the commit the changes, give me a sec...

**Comment by tarehart** [comment]
Lookin good!

**Comment by VirxEC** [comment]
All done! Ready to merge!

**Comment by Darxeal** [comment]
While you're at it, can you please add Triple Threat 2019 highlights and Hoopshot dropshot higlights? https://youtu.be/ibYH3J8D3ko and https://youtu.be/_jBciVyTZz4

**Comment by VirxEC** [comment]
image

**Comment by VirxEC** [comment]
I want to wait a bit & see if time makes me discover any bugs or if anyone else has feedback

**Comment by Darxeal** [comment]
You can put the hoopshot highlights under Day 1 because they're dropshot only

**Comment by VirxEC** [comment]
image

**Review by IamEld3st — APPROVED** [review]

**Pull request merged**
