### PR TITLE
Updated tournament page to include all official tournaments

### PR DESCRIPTION
**Pull request by NicEastvillage**
Some charity links are still missing.

### CODE REVIEW

**Comment by skyborgff** [comment]
something here, like the newest tournament logo would look better and call for attencion
https://gyazo.com/4c9ff359362e4fcd909d81e867c83cd7

adding "join the discord to get notified of smaller tournaments" would be helpfull
https://gyazo.com/8e255bddd99c200c23e7313068ba13b7

**Comment by NicEastvillage** [comment]
Good suggestions. The sidebar card was a bit empty. Now looks like this
billede
and smaller tournaments and events on discord are mentioned
billede

**Comment by skyborgff** [comment]
Discord server should be a link

**Comment by NicEastvillage** [comment]
There's a server thingy right next to it, but sure!

**Comment by skyborgff** [comment]
@tarehart only RLBot 2018 Official August Tournament has charity, shouldnt we add to all that had it?

**Comment by tarehart** [comment]
Sorry, skiing. Here's one https://anython.com/goals-for-direct-relief-in-the-rocket-league-ai-tournament-9346?eventHome=Yes

Here's another https://anython.com/reliefbot-goes-to-the-rocket-bot-championship?eventHome=Yes

Here's the big one https://anython.com/rocket-league-robo-goals-for-disaster-relief?eventHome=Yes

**Pull request merged**
